name: chuck_example
description: Demonstrates how to use the Chuck Interceptor plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  path_provider:
  connectivity_plus: ^6.0.3
  chuck_interceptor:
    path: ../

dev_dependencies:
  build_runner:
  chopper_generator:
  lints: ^4.0.0
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
